# Generated by Django 4.0.3 on 2022-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
