# Generated by Django 4.0.3 on 2022-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dateOfCreated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dateOfUpdated',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique_for_date='dateOfPublish'),
        ),
    ]
