# Generated by Django 4.0.3 on 2022-04-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=150), max_length=150, unique_for_date='dateOfPublish'),
        ),
    ]
