# Generated by Django 4.0.3 on 2022-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='beforeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(unique=True)),
                ('userPassword', models.TextField()),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formEmail', models.EmailField(max_length=254)),
                ('formMessage', models.TextField()),
            ],
        ),
    ]
