# Generated by Django 4.0.3 on 2022-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_beforeuser_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeuser',
            name='userActive',
            field=models.IntegerField(default=0),
        ),
    ]
